# Create a crm_data.yml file (or rename this one!) formatted just like this one and fill in the fields with your specific values.
# The 'token' value is the API key that is provided to each BatchBook account. This is the main bridge between the app and your BatchBlue data.
# The 'per_request' value is the maximum number of objects you wish to retrieve for collection requests. A very high number may cause requests to time out.
# The 'ra_feed_url' value is the feed URL for recent activities used in the log_activities rake task. Only necessary case you use the rake task.
development:
    account: test
    token: zzzxxx777cccc
    per_request: 100
    ra_feed_url: https://myacc.batchbook.com/feeds/kjkjhJHjHJhjHjhJH/activity_log.atom
production:
    account: test
    token: zzzxxx777cccc
    per_request: 100
    ra_feed_url: https://myacc.batchbook.com/feeds/kjkjhJHjHJhjHjhJH/activity_log.atom


